dist: trusty
sudo: false
language: cpp

addons:
 apt:
  sources:
    -ubuntu-toolchain-r-test
  packages:
    -g++-10

script:
  -cd src/Client/
  -cmake --build .
  -cd ../Server/
  -cmake --build .
