os:
  - linux

language: cpp

dist: bionic
sudo: require

addons:
  apt:
    update: true 
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++
      - qt5-default   
      - libmariadb-dev
      - libmariadbclient-dev

script:
  - export CC=gcc-9 
  - export CXX=g++-9 
#  - source /opt/qt510/bin/qt510-env.sh
  - cd src/Client
  - mkdir build
  - cd build
  - cmake ..
  - make 
  - cd ../../Server
  - mkdir build
  - cd build 
  - cmake ..
  - make 

