os:
  - linux

language: cpp

dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
    packages:
      - gcc-9
      - g++-9
      - qt510-meta-minimal
      - qt510svg
      - qt510imageformats
      - qt510tools   

before_install:
  - git clone https://github.com/mysql/mysql-connector-cpp
  - cmake mysql-connector-cpp 
 # - cmake --build . --target install  

script:
  - export CC=gcc-9 
  - export CXX=g++-9 
  - source /opt/qt510/bin/qt510-env.sh
  - cd src/Client/
  - mkdir build
  - cd build
  - cmake ..
  - make 
  - cd ../../Server
  - mkdir build
  - cd build 
  - cmake ..
  - make 
