dist: trusty

language: cpp

addons:
	apt:
	packages:
		- gcc-10

script:
    - sudo ln -s /usr/bin/gcc-10 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-10 /usr/local/bin/g++
    - export CC=/usr/bin/gcc-10
    - export CXX=/usr/bin/g++-10
