os:
  - linux

language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
    packages:
      - gcc-7
      - g++-7
      - qt510-meta-minimal
      - qt510svg
      - qt510imageformats
      - qt510tools


script:
  - export CC=gcc-7 
  - export CXX=g++-7 
  - source /opt/qt510/bin/qt510-env.sh
  - cd src/Client/
  - mkdir build
  - cd build
  - cmake ..
  - make 
  - cd ../../Server/
  - mkdir build 
  - cd build 
  - cmake ..
  - make
  - cmake --version
  - qmake --version


